### ISSUE TITLE
DUDE

### ISSUE THREAD

**Issue by jknppp** [PiSaucer/v2-windows-93-repo#1]
ARE YOU SERIOUS ????
STOP THAT

**Comment by pokazef** [comment]
Wat

**Comment by jknppp** [comment]
@PiSaucer
Please, can you not share our source without any authorization?
Windows93 is our project, not yours.

**Comment by PiSaucer** [comment]
At least open your window 93 project. I will not uploading the files. I am just doing this so I play on the amazing website you guys put out for us at my school because they block it. Sorry for all the problems if you really want me to delete the repo then please have some of the others from the project ask well in here. 
-PiSaucer

**Comment by jknppp** [comment]
@PiSaucer -> http://www.windows93.net/c/proof.png
In case you didn't understand it yet: I'm the owner of windows93.net and I ask you to remove v1 and v2 from your repos. I'll upload my source on github when I want to, I don't need ppl to do it for me. Windows93 is our project, not yours. Thanks.

**Comment by PiSaucer** [comment]
thank you for proof, i will delete it now
